[CN-1287]: add create license step
hazelcast-guides/hazelcast-platform-operator-expose-externally pull request #23
Opened 2024-06-26 12:58 UTC by kutluhanmetin

2024-06-27 14:36 UTC, hasancelik requested changes

2024-06-27 14:36 UTC, hasancelik commented on docs/modules/ROOT/pages/hazelcast-platform-operator-expose-externally.adoc
>  * Deployed xref:operator:ROOT:get-started.adoc[Hazelcast Platform Operator]
https://github.com/hazelcast-guides/hazelcast-platform-operator-jet/pull/5#discussion_r1657255386

2024-07-02 07:54 UTC, kutluhanmetin commented on docs/modules/ROOT/pages/hazelcast-platform-operator-expose-externally.adoc
>  * Deployed xref:operator:ROOT:get-started.adoc[Hazelcast Platform Operator]
https://github.com/hazelcast-guides/hazelcast-platform-operator-expose-externally/pull/23/commits/12999fd03b2ff37a9c1a663d0074ed61c7e6645b

2024-07-02 10:28 UTC, hasancelik approved these changes

2024-07-02 11:56 UTC, merged